"""Shared application constants."""

APP_NAME = "AI Barrage Companion"
APP_SHORT_NAME = "ABC"
DEFAULT_CAPTURE_INTERVAL_SECONDS = 4.0
DEFAULT_BARRAGE_DURATION_SECONDS = 8.0
DEFAULT_API_TIMEOUT_SECONDS = 20.0
