"""Shared application constants."""

APP_NAME = "AI Barrage Companion"
APP_SHORT_NAME = "ABC"
DEFAULT_CAPTURE_INTERVAL_SECONDS = 4.0
DEFAULT_BARRAGE_DURATION_SECONDS = 8.0
DEFAULT_API_TIMEOUT_SECONDS = 20.0
DEFAULT_DUPLICATE_WINDOW_SECONDS = 10.0
DEFAULT_MIN_BARRAGE_SPEED = 80.0
DEFAULT_TRACK_HEIGHT = 36
DEFAULT_TRACK_GAP = 12
DEFAULT_SETTINGS_FILENAME = "abc-settings.json"
DEFAULT_AI_BARRAGE_COUNT = 3
DEFAULT_RENDER_TICK_MS = 100
DEFAULT_BARRAGE_SEND_INTERVAL_MS = 1200
DEFAULT_BARRAGE_BUFFER_LIMIT = 10
DEFAULT_DISPLAY_AREA_PERCENT = 65
DEFAULT_BARRAGE_FONT_SIZE = 18
